### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by ishantanu** [remony/instashutter#1]
The project is giving me 404 error on opening the url.

**Comment by aniketxpp** [comment]
I am also facing the same error after compiling in netbeans

**Comment by stuartjdouglas** [comment]
Hi guys, sorry for the wait, I just checked there. seems like I was using deprecated things at the time I was developing this. If you get errors when compiling it seems like it likes due to requiring java .7 source. I have made a commit that makes it works, as noted below it requires Cassandra 2.2.5 it will not work on the 3.x releases. Hopefully this will now work.

If it still doesn't work below is what i did to make it work on my system: (windows 10)

Add

```
<properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>
```

to the pom.xml, it just forces the compiler to use 1.8 instead of whatever netbeans uses. 

In regards to the 404 errors, this is from what I'm getting due to the application not seeing the Cassandra database, however this is because it will only work with 2.x releases. Note 2.2.5 release works :smile:
